name: build


on:
  push:
    branches:
      - main
      - develop
      - feature/ci
      - feature/ut

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: |
        cd src
        npm install
        npm run build --if-present