name: Release

on:
  release:
    types: [published]
  push:
    branches:
      - "publish"
      
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET 3.0 for gitreleasemanager
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.x
      - name: Setup .NET 5.0 for Release Manager
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11
        with:
          useConfigFile: true
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
          architecture: 'x64'
      - name: run package all
        run: |
          cd src
          pipenv install
          pipenv run invoke pack-all --version ${{ steps.gitversion.outputs.MajorMinorPatch }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            src/packages/
      - uses: gittools/actions/gitreleasemanager/setup@v0.9.11
        name: Install GitReleaseManager
        with:
          versionSpec: "0.11.x"
      - uses: gittools/actions/gitreleasemanager/addasset@v0.9.11
        name: Add asset to a release with GitReleaseManager
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: "IC-Naming"
          repository: "icnaming-browser-extensions"
          tagName: "v${{ steps.gitversion.outputs.MajorMinorPatch }}"
          assets: |
            src/packages/icnaming-browser-extension-${{ steps.gitversion.outputs.MajorMinorPatch }}.zip
